
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.8 Generated source
 * version: 2.2
 * 
 */
@WebService(name = "SOAPDemoSoap", targetNamespace = "http://tempuri.org")
@XmlSeeAlso({ org.tempuri.ObjectFactory.class })
public interface SOAPDemoSoap {

	/**
	 * 
	 * @param name
	 * @return returns org.tempuri.ArrayOfPersonIdentificationPersonIdentification
	 */
	@WebMethod(operationName = "GetListByName", action = "http://tempuri.org/SOAP.Demo.GetListByName")
	@WebResult(name = "GetListByNameResult", targetNamespace = "http://tempuri.org")
	@RequestWrapper(localName = "GetListByName", targetNamespace = "http://tempuri.org", className = "org.tempuri.GetListByName")
	@ResponseWrapper(localName = "GetListByNameResponse", targetNamespace = "http://tempuri.org", className = "org.tempuri.GetListByNameResponse")
	public PersonIdentificationList getListByName(
			@WebParam(name = "name", targetNamespace = "http://tempuri.org") String name);

}
